### ISSUE TITLE
Setting for the default tab to open when the app opens.

### ISSUE THREAD

**Issue by magnus-ISU** [mueller-ma/TabletopTools#152]
Pretty basic, I think.

**Comment by Kardelio** [comment]
Hello again! Its been a whole year already since the last Hacktoberfest! Really loved this project last year so hunted it straight back out! Found this issue and would love to pick it up if no one else has yet...
If so would you be able to give me some more information on this? Aka which tab to set as default or is it that the user decides which tab etc... thanksx

**Comment by mueller-ma** [comment]
You can add a preference where the user can select any other fragment (excluding preference) as default view. Default should be `DicesFragment`.

**Comment by Kardelio** [comment]
@mueller-ma thanks so much! Ill get on it! Is there a specific place or way that you would like the UI for this?

**Comment by mueller-ma** [comment]
I think a ListPreference in the settings would be the best solution.

**Comment by neil0504** [comment]
Hello @mueller-ma @magnus-ISU , I would like to work on the issue if its not assigned to anyone.

**Comment by mueller-ma** [comment]
@Kardelio is already assigned on this issue.

**Comment by Kardelio** [comment]
@mueller-ma ^ let me know what you think
